export const RESERVATION_STATUS = {
  PENDING: 1,
  CONFIRMED: 2,
  CANCELLED: 3,
};

export const RESERVATION_STATUS_NAMES = {
  [RESERVATION_STATUS.PENDING]: "Pending",
  [RESERVATION_STATUS.CONFIRMED]: "Confirmed",
  [RESERVATION_STATUS.CANCELLED]: "Cancelled",
};
